version: 2
registries:
  npm-registry:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.GH_TOKEN}}
    replaces-base: true

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/"
    registries:
      - npm-registry
    schedule:
      interval: "daily"
      time: "23:50"
    open-pull-requests-limit: 8
