yarnPath: .yarn/releases/yarn-3.4.1.cjs

nodeLinker: node-modules

npmScopes:
  "@zwirner/design-system":
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_TOKEN}"
    npmRegistryServer: "https://registry.npmjs.org/"