services:
  zwirnerweb:
    build:
      context: ./
    volumes:
      - .:/app
      - zwirner:/app/node_modules
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development

volumes:
  zwirner:
