name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: "yarn"
      - run: yarn install --immutable
        env:
          GH_TOKEN: ${{ secrets.READ_GH_PACKAGES_TOKEN }}
      - run: yarn prettier --check .
  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: "yarn"
      - run: yarn install --immutable
        env:
          GH_TOKEN: ${{ secrets.READ_GH_PACKAGES_TOKEN }}
      - run: yarn type-check
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: "yarn"
      - run: yarn install --immutable
        env:
          GH_TOKEN: ${{ secrets.READ_GH_PACKAGES_TOKEN }}
          SKIP_ENV_CHECK: true
      - run: yarn lint
        env:
          SKIP_ENV_CHECK: true
  test_e2e:
    name: Playwright tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          # TODO get GH Actions to respect .tool-version
          node-version: 19
          cache: "yarn"
      - run: yarn install --immutable
        env:
          GH_TOKEN: ${{ secrets.READ_GH_PACKAGES_TOKEN }}
      - run: yarn playwright install --with-deps
      - name: Wait for Vercel preview deployment to be ready
        uses: patrickedqvist/wait-for-vercel-preview@v1.3.1
        id: waitFor200
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 600
      - name: Run tests
        run: yarn test:e2e
        env:
          PLAYWRIGHT_TEST_BASE_URL: ${{ steps.waitFor200.outputs.url }}
